DEFAULT_ERROR="Something went wrong!"
USERNAME_VALID_ERROR_MSG="{'username': [ErrorDetail(string='A user with that username already exists.', code='unique')]}"
